// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAD8NHfsHdz0Ge7rzOhdCdpdSOmw_t8Hs',
    appId: '1:62293553167:web:c27085258afd86407a337a',
    messagingSenderId: '62293553167',
    projectId: 'practical-test-78775',
    authDomain: 'practical-test-78775.firebaseapp.com',
    databaseURL: 'https://practical-test-78775.firebaseio.com',
    storageBucket: 'practical-test-78775.appspot.com',
    measurementId: 'G-KXES68VQ6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhIKhf_PJq77sMd7WhFV4JoG_NPfiO39I',
    appId: '1:62293553167:android:154a20269481f2f27a337a',
    messagingSenderId: '62293553167',
    projectId: 'practical-test-78775',
    databaseURL: 'https://practical-test-78775.firebaseio.com',
    storageBucket: 'practical-test-78775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIKWhdp9OfmlUhFDjPMEOIoD34l1UWJuw',
    appId: '1:62293553167:ios:301abdac760089037a337a',
    messagingSenderId: '62293553167',
    projectId: 'practical-test-78775',
    databaseURL: 'https://practical-test-78775.firebaseio.com',
    storageBucket: 'practical-test-78775.appspot.com',
    androidClientId: '62293553167-9gu52o00ct4o40g2bojh0rne8cn3drj1.apps.googleusercontent.com',
    iosClientId: '62293553167-bj6u44scfnlljlk3ucvc4l6f6ntcapmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIKWhdp9OfmlUhFDjPMEOIoD34l1UWJuw',
    appId: '1:62293553167:ios:301abdac760089037a337a',
    messagingSenderId: '62293553167',
    projectId: 'practical-test-78775',
    databaseURL: 'https://practical-test-78775.firebaseio.com',
    storageBucket: 'practical-test-78775.appspot.com',
    androidClientId: '62293553167-9gu52o00ct4o40g2bojh0rne8cn3drj1.apps.googleusercontent.com',
    iosClientId: '62293553167-bj6u44scfnlljlk3ucvc4l6f6ntcapmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAD8NHfsHdz0Ge7rzOhdCdpdSOmw_t8Hs',
    appId: '1:62293553167:web:cbec6cd5bd8750307a337a',
    messagingSenderId: '62293553167',
    projectId: 'practical-test-78775',
    authDomain: 'practical-test-78775.firebaseapp.com',
    databaseURL: 'https://practical-test-78775.firebaseio.com',
    storageBucket: 'practical-test-78775.appspot.com',
    measurementId: 'G-17NJRNBXD3',
  );
}
